export const paramsTraductions = {
    en: {
        add: 'Ajouter',
        addAdmin: 'Ajouter un administrateur',
        addind: 'Ajout...',
        admin: 'Administrateur',
        allAdmin: 'Tous les administrateurs',
        confirm: 'Confirmez votre mot de passe',
        delete: 'Supprimer',
        email: 'Email',
        editProfile: 'Editer un profil',
        logout: 'Se déconnecter',
        noAdmin: 'Aucun admin pour l\'instant',
        password: 'Mot de passe',
        teacher: 'Enseignant',
        username: 'Pseudo',
        saving: 'Enregistrement',
        save: 'Enregistrer',
        cancel: 'Annuler',
        selectSex: '--- Selectionner le sexe de l\'enseignant ----',
        m: 'Masculin',
        f: 'Féminin',
        sex: 'Sex de l\'enseignant',
        teacherName: 'Nom de l\'enseignagnt :',
        teacherSubname: 'Prénom de l\'ensignant :',
        number: 'Numéro de téléphone de l\'enseignant :',
    },
    fr: {
        add: 'Ajouter',
        addAdmin: 'Ajouter un administrateur',
        addind: 'Ajout...',
        admin: 'Administrateur',
        allAdmin: 'Tous les administrateurs',
        confirm: 'Confirmez votre mot de passe',
        delete: 'Supprimer',
        email: 'Email',
        editProfile: 'Editer un profil',
        logout: 'Se déconnecter',
        noAdmin: 'Aucun admin pour l\'instant',
        password: 'Mot de passe',
        teacher: 'Enseignant',
        username: 'Pseudo',
        saving: 'Enregistrement',
        save: 'Enregistrer',
        cancel: 'Annuler',
        selectSex: '--- Selectionner le sexe de l\'enseignant ----',
        m: 'Masculin',
        f: 'Féminin',
        sex: 'Sex de l\'enseignant',
        teacherName: 'Nom de l\'enseignagnt :',
        teacherSubname: 'Prénom de l\'ensignant :',
        number: 'Numéro de téléphone de l\'enseignant :',
    }
}