export const sectionTraductions = {
    en: {
        addSection: 'Ajouter une section',
        editdSection: 'Ajouter une section',
        secName: 'Nom du section',
        type: 'Type de la section',
        addSeq: 'Veuillez ajouter des sequences pour continuer',
        selectSeq: 'Selectionner les séquences',
        close: 'Fermer (Annuler)',
        save: 'Enregistrer',
        visite: 'Visiter',
        saving: 'Enregistrement...',
        name: 'Nom',
        action: 'Actions',
        noSection: 'Aucune section !',
        seeClass: 'Visiter la section',
        delete: 'Supprimer',
        deleting: 'Suppression...',
        edit: 'Editer',
    },
    fr: {
        addTrim: 'Ajouter une section',
        trimName: 'Nom du section',
        type: 'Type de la section',
        addSeq: 'Veuillez ajouter des sequences pour continuer',
        selectSeq: 'Selectionner les séquences',
        close: 'Fermer (Annuler)',
        save: 'Enregistrer',
        visite: 'Visiter',
        saving: 'Enregistrement...',
        name: 'Nom',
        action: 'Actions',
        noSection: 'Aucune section !',
        seeClass: 'Visiter la section',
        delete: 'Supprimer',
        deleting: 'Suppression...',
        edit: 'Editer',
    }
}